parameters:
    cache.file_paths:
        - verification_hash:
            - hashes.txt

services:
    file: #služi kao wrapper za resource file od naznačenog cacha u cache.file_paths
        class: Locastic\CoreBundle\Tools\File

    user_repository:
        class: Locastic\CoreBundle\Repositories\UserRepository
        arguments: [@doctrine]

    cache:
        class: Locastic\CoreBundle\Tools\Cache
        arguments: [%cache.file_paths%, @file]

    custom_user_provider:
        class: Locastic\CoreBundle\Security\CustomUserProvider
        arguments: [@service_container, @kernel]

    listener.auth_success_listener:
        class: Locastic\PublicBundle\Listeners\AuthListener
        arguments: [@user_repository]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onAuthenticationSuccess }