locastic_authorized:
    resource: "@LocasticAuthorizedBundle/Resources/config/routing.yml"
    prefix:   /

locastic_core:
    resource: "@LocasticCoreBundle/Resources/config/routing.yml"
    prefix:   /

locastic_public:
    resource: "@LocasticPublicBundle/Resources/config/routing.yml"
    prefix:   /

login:
    path:     /login
    defaults: { _controller: LocasticPublicBundle:Login:login }

login_check:
    path: /login_check

logout:
    path: /logout


