security:
    encoders:
        App\ToolsBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_USER:   [ROLE_USER, ROLE_ALLOW_TO_SWITCH]

    providers:
        users:
            entity: { class: LocasticCoreBundle:User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                always_use_default_target_path: true
                default_target_path: locastic_dashboard
                post_only: true
                login_path: login
                check_path: login_check
            logout:
                path:   /logout
                target: /unauthorized

    access_control:
        - { path: ^/unauthorized$ , roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$ , roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: [ROLE_USER] }