locastic_dashboard:
    path: /
    defaults: { _controller: LocasticAuthorizedBundle:Dashboard:dashboard }
    methods: [GET]

locastic_addList:
    path: /list-managment/add-list
    defaults: { _controller: LocasticAuthorizedBundle:Rest:addList }
    methods: [POST]


locastic_getLists:
    path: /list-managment/get-lists
    defaults: { _controller: LocasticAuthorizedBundle:Rest:getLists }
    methods: [POST]
