locastic_dashboard:
    path: /
    defaults: { _controller: LocasticAuthorizedBundle:Dashboard:dashboard }
    methods: [GET]

locastic_getLists:
    path: /list-managment/add-list
    defaults: { _controller: LocasticAuthorizedBundle:Rest:addList }
    methods: [POST]
