locastic_dashboard:
    path: /
    defaults: { _controller: LocasticAuthorizedBundle:Dashboard:dashboard }
    methods: [GET]

locastic_getLists:
    path: /
    defaults: { _controller: LocasticAuthorizedBundle:Dashboard:getLists }
    methods: [POST]
