locastic_dashboard:
    path: /
    defaults: { _controller: LocasticAuthorizedBundle:Dashboard:dashboard }
    methods: [GET]

locastic_addList:
    path: /list-managment/add-list
    defaults: { _controller: LocasticAuthorizedBundle:Rest:addList }
    methods: [POST]


locastic_getLists:
    path: /list-managment/get-items
    defaults: { _controller: LocasticAuthorizedBundle:Rest:getItems }
    methods: [POST]

locastic_addTask:
    path: /task-managment/add-task
    defaults: { _controller: LocasticAuthorizedBundle:Rest:addTask }

locastic_getTasks:
    path: /task-managment/get-task
    defaults: { _controller: LocasticAuthorizedBundle:Rest:getItems }

locastic_deleteTask:
    path: /task-managment/delete-task
    defaults: { _controller: LocasticAuthorizedBundle:Rest:deleteTask }
