services:
    list_repository:
        class: Locastic\CoreBundle\Repositories\ListRepository
        arguments: [@doctrine]

    order_repository:
        class: Locastic\CoreBundle\Repositories\OrderRepository
        arguments: [@doctrine]

    task_repository:
        class: Locastic\CoreBundle\Repositories\TaskRepository
        arguments: [@doctrine]
