locastic_public_unauthorized:
    path:     /unauthorized
    defaults: { _controller: LocasticPublicBundle:Public:unauthorized }

locastic_public_registration:
    path:     /registration
    defaults: { _controller: LocasticPublicBundle:Registration:registration }
