services:
    listener.is_authenticated_service:
        class: Locastic\PublicBundle\Listeners\AuthenticationListener
        arguments: [ @service_container ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
